### ISSUE TITLE
You don't honour locale

### ISSUE THREAD

**Issue by atkinsroy** [jdhitsolutions/PSCalendar#22]
PowerShell uses the US locale by default for dates, which you're using. Most English speaking locales use dd/mm/yyyy. Normally, I wouldn't mind, but this is a module all about dates!

**Comment by atkinsroy** [comment]
example:
PS7.1.3 C:\> Use-Culture en-AU { Show-Calendar -HighlightDate 26/7/2021 }  #26th July
   
=-=-=-=-=-=-=-=-=-=- en-AU - English (Australia) -=-=-=-=-=-=-=-=-=-=
Invoke-Command : Cannot process argument transformation on parameter 'HighlightDate'. Cannot convert value "26/7/2021" to type "System.DateTime[]". Error: "Cannot convert value "26/7/2021" to type "System.DateTime". Error: "String '26/7/2021' was not recognized as a valid DateTime.""
At Module.psm1:927 char:17
+                 Invoke-Command $Script
+                 ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Invoke-Command], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Microsoft.PowerShell.Commands.InvokeCommandCommand
PS7.1.3 C:\>

**Comment by jdhitsolutions** [comment]
Do you have the same issue when using Windows PowerShell?

**Comment by atkinsroy** [comment]
Yes, same result:
![image](https://user-images.githubusercontent.com/6621844/125020547-63563680-e0bc-11eb-8774-17f73867dfe2.png)

**Comment by jdhitsolutions** [comment]
I think I'm close. Part of my testing problem is a bug I think in PowerShell 7. This is what I see in Windows PowerShell which as far as I know is correct.

![image](https://user-images.githubusercontent.com/12089920/125092226-1e6fd700-e09f-11eb-8acb-b6aa4884dda0.png)

But in PowerShell 7 I get a different first day of the week.

![image](https://user-images.githubusercontent.com/12089920/125092182-12841500-e09f-11eb-9d4e-23b636bbbe80.png)

**Comment by jdhitsolutions** [comment]
I'm chasing down a potential .NET bug with Microsoft. This command

```powershell
[System.Globalization.CultureInfo]::GetCultureInfo("en-au").DateTimeFormat.firstdayofWeek
```

Gives me different results between Windows PowerShell and PowerShell 7. If you try do you get the same first day in both PowerShell versions?

**Comment by atkinsroy** [comment]
Yes. I get the same thing:
![image](https://user-images.githubusercontent.com/6621844/125149029-cbb71d80-e179-11eb-8e7c-2fed7a5093a2.png)
![image](https://user-images.githubusercontent.com/6621844/125149040-da053980-e179-11eb-87fb-92bf7e613bd9.png)

**Comment by jdhitsolutions** [comment]
That is good and bad. At least I now know there is a bug in PowerShell 7 or at least .NET Core. The bad news is that I am relying on this information to know when to start the week.

**Comment by atkinsroy** [comment]
Understood. Onwards and upwards.

**Comment by jdhitsolutions** [comment]
I have some ideas on how to work around this but it will mean some re-working of the command. In the meantime, I pushed v2.1.0 to the PowerShell Gallery. Update the module and run in Windows PowerShell. Everything should work as it should for you.

**Comment by atkinsroy** [comment]
It works as expected.  Small issue - There is an error where you are using out-file to a non-existent "d" drive (on my system). This only appears when  -HighLightDate is specified. Probably a debug check you forgot to remove.

**Comment by jdhitsolutions** [comment]
What expression are you running and what is the error message?

**Comment by atkinsroy** [comment]
```
PS5.1.19041.1023 C:\> Show-Calendar -HighlightDate 29/7
out-file : Could not find a part of the path 'D:\temp\d.txt'.
At ...\Modules\PSCalendar\2.1.0\functions\private.ps1:21 char:27
+         $highlightDates | out-file d:\temp\d.txt
+                           ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```
otherwise, output is as expected:
![image](https://user-images.githubusercontent.com/6621844/125403745-345ffd80-e3f9-11eb-8ba4-f7d042b0836d.png)

**Comment by jdhitsolutions** [comment]
I see now what the problem is with the temp file.

**Comment by atkinsroy** [comment]
works with both versions of PS. Thanks Jeff.
